### PR TITLE
Translation key for forgot password wrong email

### PR DESCRIPTION
**Pull request by dannimajdalani**
## New or changed source translation strings

| Source String                | Location or PR in a Vanilla repository
|------------------------------|----------------------------------------
|    'Couldn\'t find an account associated with that email/username.'                          |tx-source/site_core.php

### CODE REVIEW

**Comment by vrjrobitaille** [comment]
I see that this commit is live on my customers cluster; however, the string is still not translated on the customers site. I've checked Transifex as well and cannot find a string that match:

screen shot 2018-05-28 at 12 52 43 pm


screen shot 2018-05-28 at 12 52 34 pm

screen shot 2018-05-28 at 12 52 34 pm

**Comment by dannimajdalani** [comment]
This PR was to add the key to the requested string. It still need to be translated from transifex.

**Comment by vrjrobitaille** [comment]
That's the problem, I can't find the string in Transifex. Is there a process that needs to happen in order for this to make it onto Transifex?

**Comment by vrjrobitaille** [comment]
@dannimajdalani Any ideas?

**Pull request merged**
